services:
  db:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
      # Usamos esto en lugar de 'secrets:' para aplicar el :Z de SELinux
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password:ro
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -p\"$(cat /run/secrets/db_root_password)\" --silent"]
      interval: 5s
      timeout: 5s
      retries: 25
      start_period: 120s
  backend:
    build:
      context: ./requirements/nest
    container_name: nest_backend
    restart: always
    depends_on:
      db: 
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - PORT=3000
    volumes:
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ../secrets/jwt_secret.txt:/run/secrets/jwt_secret:ro
      - ../secrets/ssl/localhost.crt:/run/secrets/ssl_cert:ro
      - ../secrets/ssl/localhost.key:/run/secrets/ssl_key:ro
      
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./requirements/svelte
    container_name: svelte_frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ../secrets/ssl/localhost.crt:/run/secrets/ssl_cert:ro
      - ../secrets/ssl/localhost.key:/run/secrets/ssl_key:ro
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 5173"]

  backuper:
    image: debian:latest
    container_name: backup-container
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      frontend:
        condition: service_healthy
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "8080:8080"
    networks:
      - transcendence_net
    volumes:
      - ./backups/recovery.sh:/tmp/recovery.sh:Z
      - ./requirements/backuper/tools:/usr/local/bin:Z 
      - ./requirements/backuper/srcs/index.html:/var/www/html/index.html:Z 
      - ./backups:/backups:Z
      - mariadb_data:/var/lib/mysql
      - ../secrets/db_password.txt:/run/secrets/db_password:ro,Z
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password:ro,Z
      - ../secrets/db_password.txt:/run/secrets/db_password:ro,Z
      - ../secrets/jwt_secret.txt:/run/secrets/jwt_secret:ro,Z
      - ../secrets/ssl/localhost.crt:/run/secrets/ssl_cert:ro,Z
      - ../secrets/ssl/localhost.key:/run/secrets/ssl_key:ro,Z
      - ../secrets/ssl/localhost.crt:/run/secrets/ssl_cert:ro,Z
      - ../secrets/ssl/localhost.key:/run/secrets/ssl_key:ro,Z
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: bash /usr/local/bin/entrypoint.sh

volumes:
  mariadb_data:

networks:
  transcendence_net:
    driver: bridge
