FROM node:20-alpine

WORKDIR /app

COPY *.json ./

RUN npm install
RUN npm run build
RUN apk add --no-cache wget

COPY ./tools/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/entrypoint.sh"]
CMD ["node", "dist/main.js"]
