# node:20-alpine es eficiente y segura
FROM node:20-alpine

WORKDIR /app

# Instalamos dependencias primero para aprovechar la caché de capas
#COPY package*.json ./
#RUN npm install

# Copiamos el resto del código
COPY . .

# Compilamos el proyecto NestJS
RUN npm run build

# Exponemos el puerto del backend (habitualmente 3000)
EXPOSE 3000

# Comando para ejecutar en desarrollo (puedes cambiarlo a node dist/main si es prod)
CMD ["npm", "run", "start:dev"]
