FROM node:20-alpine

WORKDIR /app

COPY * ./

RUN npm install && npm install mysql2
COPY . .
RUN npm run build
RUN apk add --no-cache wget

COPY ./tools/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/entrypoint.sh"]
CMD ["node", "dist/main.js"]
