global:
  scrape_interval: 15s # Cada cuánto tiempo pide datos (15s es el estándar)
  evaluation_interval: 15s # Cada cuánto tiempo evalúa las reglas de alerta

scrape_configs:
  # 1. Vigilarse a sí mismo (útil para ver si Prometheus está sano)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Vigilar tu App de NestJS
  - job_name: 'nest_backend'
    metrics_path: '/metrics' # Ruta donde NestJS escupe los números
    static_configs:
      - targets: ['nest_backend:3000'] # Usa el container_name de tu app
